📝 :: 피클 좋아요 기능 구현
MaeumgaGym/MaeumGaGym_Backend pull request #116
Opened 2024-01-26 08:21 UTC by Daybreak312

- PickleLike Entity에서 Pickle과의 매핑 제거
- 피클 좋아요 기능 구현

2024-01-26 08:23 UTC, gurdl0525 commented
join은 왜 풀어둔거에요?

2024-01-26 08:41 UTC, Daybreak312 commented
> join은 왜 풀어둔거에요?


좋아요를 가공하는 경우는 모두 피클을 이미 Select한 이후에 작업을 해야하기 때문에 필요하지 않은 의존성이라 생각해 제거했습니다

2024-01-26 08:47 UTC, gurdl0525 approved these changes

2024-01-26 10:42 UTC, gurdl0525 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleLikeJpaEntity.kt
>  @Entity(name = TableNames.PICKLE_LIKE_TABLE)
복합키 쓰지말고 AI인 PK하나 만들어주시고
UK_INDEX(user_id, pickle_id) 설정 해주세요

2024-01-26 10:49 UTC, gurdl0525 requested changes
UK설정 적용해주세연

2024-01-30 02:59 UTC, gurdl0525 approved these changes

2024-01-30 05:34 UTC, merged