✨ :: RoutineHistory 생성 API
MaeumGaGym/MaeumGaGym_Backend pull request #152
Opened 2024-03-10 14:38 UTC by gurdl0525

- RoutineHistory Table 생성
- Today Routine 보기 API 일부 변경
- RoutineHistory 생성 API 추가

2024-03-10 14:43 UTC, gurdl0525 commented
현재 toResponse의 isComplete가 history의 존재 여부로 판단되고 있는데
추후에 is_completed 컬럼을 루틴 테이블에 추가하여 Query횟수를 줄이도록 해요. 😉
↑ 보시면 Asana Issue 생성 부탁드려요 🙏🙏🙏

2024-03-11 02:41 UTC, Daybreak312 requested changes

2024-03-11 02:41 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
> +    const val ROUTINE_HISTORY_DATE_USER_UNIQUE = UNIQUE_PREFIX + "date_user"
조금 길어지기는 한데 routine_history_date로 작성하는 게 더 좋아보입니다.

2024-03-11 02:41 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/entity/RoutineHistoryJpaEntity.kt
> +        protected set
updatable = false 명시해주세요

2024-03-11 02:41 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CompleteRoutineService.kt
> +) : CompleteTodayRoutineUseCase {
네이밍 일치시켜주세요 -> CompleteTodayRoutineService

2024-03-11 02:41 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CompleteRoutineService.kt
> +            throw BusinessLogicException(409, "Already Completed Routine")
409보단 완료를 취소하는 게 나아보입니다
지금은 History를 제거하고, 추후 isCompleted 컬럼이 추가되면 boolean 수정하는 식으로 진행해주세요

2024-03-11 02:41 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/Exceptions.kt
> +        val NO_CONTENT = MaeumGaGymException(204, "There is no Content")
다른 204 Exception처럼 There's No Content Left로 통일해주시면 좋을 것 같습니다

2024-03-11 02:41 UTC, Daybreak312 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
> +    private val locationHeaderSubjectManager: LocationHeaderSubjectManager,
이 필드는 맨 아래로 내려주세요

2024-03-11 02:45 UTC, gurdl0525 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
> +    const val ROUTINE_HISTORY_DATE_USER_UNIQUE = UNIQUE_PREFIX + "date_user"
아래 다른 인덱스들 보시면 테이블명 빠져있습니다.
뿐만 아니라 인덱스 자체가 테이블에 종속되기 때문에 query나 기타 등등에
routine_history_date.idx_ routine_history_date로 보여서 너무 깁니다.

2024-03-11 02:47 UTC, gurdl0525 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
> +    private val locationHeaderSubjectManager: LocationHeaderSubjectManager,
이유가 머죵..?

2024-03-11 02:48 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
> +    const val ROUTINE_HISTORY_DATE_USER_UNIQUE = UNIQUE_PREFIX + "date_user"
DAILY 제외한 모든 인덱스 테이블이 다 도메인명 명시되어 있습니다.
심지어 DAILY랑 해당 이름도 겹칩니다. 
> const val DAILY_DATE_INDEX = INDEX_PREFIX + "date"
위 필드도 같이 수정 부탁드립니다.

2024-03-11 02:48 UTC, gurdl0525 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CompleteRoutineService.kt
> +            throw BusinessLogicException(409, "Already Completed Routine")
저걸 달지 않으면 이미 history가 있음에도 select, update query가 나가게 됩니다
이런 상황 억제를 위해 if문 자체는 필요한데 throw를 하지 않을 이유가 있을까요?

2024-03-11 02:52 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CompleteRoutineService.kt
> +            throw BusinessLogicException(409, "Already Completed Routine")
피클의 좋아요 기능처럼, 좋아요를 다시 누르면 취소되듯 완료 표시를 다시 취소할 수 있는 기능을 뜻했습니다.

2024-03-11 02:54 UTC, Daybreak312 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
> +    private val locationHeaderSubjectManager: LocationHeaderSubjectManager,
제가 원하는 코드 스타일입니다. 
해당 클래스는 Controller가 매핑하려는 UseCase가 아닌 부가적인 기능이기 때문에 = Controller의 목적과 가장 관련성이 떨어지는 필드이기 때문에, 저는 가장 아래쪽에 배치하는 편입니다.

2024-03-11 02:55 UTC, gurdl0525 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
> +    const val ROUTINE_HISTORY_DATE_USER_UNIQUE = UNIQUE_PREFIX + "date_user"
이름 겹치는 건 상관 없다니까요...
<img width="335" alt="스크린샷 2024-03-11 오전 11 55" src="https://github.com/MaeumGaGym/MaeumGaGym_Backend/assets/101314072/0ab24fdc-d381-4d40-b5ed-cdbb604be62d">
위와 같이 종속되는 인덱스에 왜 테이블명 명시가 필요한지 모르겠습니다

2024-03-11 02:56 UTC, gurdl0525 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CompleteRoutineService.kt
> +            throw BusinessLogicException(409, "Already Completed Routine")
수정하겠습니다

2024-03-11 02:58 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
> +    const val ROUTINE_HISTORY_DATE_USER_UNIQUE = UNIQUE_PREFIX + "date_user"
종속된다는 것의 뜻이 파일 형태로 종속된단 뜻인 줄 몰랐습니다 😅
Resolve 하겠습니다

2024-03-11 03:01 UTC, gurdl0525 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
> +    private val locationHeaderSubjectManager: LocationHeaderSubjectManager,
혹시 이것도 문서화 사항일까요?
중요도 체크해서 매번 변경하는 것도 번거로워 보입니다.
이미 Lint로 정적분석해서 개인 코드 스타일간 충돌을 충분히 방지하고 있고,
lint로 해결하지 못하는 명명규칙 정도 까지가 생산성 대비 좋다고 봅니다.

요약해서 가성비가 떨어집니다.

2024-03-11 03:01 UTC, gurdl0525 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
> +    const val ROUTINE_HISTORY_DATE_USER_UNIQUE = UNIQUE_PREFIX + "date_user"
다른 인덱스도 테이블명 지워둘게요

2024-03-11 03:12 UTC, Daybreak312 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
> +    private val locationHeaderSubjectManager: LocationHeaderSubjectManager,
알겠습니다. Resolve 하겠습니다

2024-03-11 03:12 UTC, Daybreak312 approved these changes
LGTM 😋

2024-03-11 03:13 UTC, merged