🔀 :: ma-85 to devlop
MaeumgaGym/MaeumGaGym_Backend pull request #42
Opened 2023-12-23 23:17 UTC by gurdl0525

2023-12-24 09:25 UTC, Daybreak312 requested changes

2023-12-24 09:25 UTC, Daybreak312 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controllers/auth/AppleAuthController.kt
> +package com.info.maeumgagym.controllers.auth
복수형보다 단수형을 사용하는 게 깔끔해보일 것 같습니다

2023-12-24 09:25 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleJpaEntity.kt
> +    id: UUID? = null
피클, 루틴, 자세 등 id 유출이나 크롤링에도 피해가 없는 엔티티들은 Long Id를 사용하기로 정해졌습니다

2023-12-24 09:25 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/PickleGenerateUseCase.kt
> +    fun execute(req: PicklePostRequest)
PickleUpload...로 통일하는 게 좋을 것 같습니다.

2023-12-24 09:25 UTC, Daybreak312 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controllers/pickle/PickleController.kt
> +@RequestMapping("/pickles")
단수형 사용하는 게 깔끔할 것 같습니다

2023-12-24 09:25 UTC, Daybreak312 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controllers/pickle/PickleController.kt
> +    fun post(
pickleUpload로 통일해주세요

2023-12-24 09:25 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleJpaEntity.kt
> +    var link: String = link
model과 필드 이름이 다릅니다. 통일해주세요

2023-12-24 11:32 UTC, gurdl0525 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controllers/auth/AppleAuthController.kt
> +package com.info.maeumgagym.controllers.auth
현업 하시는분 한테 여쭤보니 다 복수형을 쓰신다고 해서요 (config도 configs를 쓴다고 함)

2023-12-24 11:33 UTC, gurdl0525 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleJpaEntity.kt
> +    id: UUID? = null
피클은 scale out 차원에서 UUID가 적합할 것 같아서 했는데, 일단 Long으로 할까요??

2023-12-24 11:34 UTC, gurdl0525 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controllers/pickle/PickleController.kt
> +@RequestMapping("/pickles")
요건 Rest 규칙에 명시 되어있는거라 다른 컨트롤러도 바꿀까 생각중입니다

2023-12-24 11:35 UTC, gurdl0525 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleJpaEntity.kt
> +    var link: String = link
넹

2023-12-24 11:35 UTC, gurdl0525 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controllers/pickle/PickleController.kt
> +    fun post(
넹

2023-12-24 11:35 UTC, gurdl0525 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/PickleGenerateUseCase.kt
> +    fun execute(req: PicklePostRequest)
넹

2023-12-24 11:59 UTC, Daybreak312 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controllers/auth/AppleAuthController.kt
> +package com.info.maeumgagym.controllers.auth
적어도 저희는 지금까지 쭉 List등의 컬렉션 변수를 제외하면 모두 단수형을 써왔기 때문에 지금은 단수형을 사용하는 게 좋을 것 같습니다. 화요일 코드 스타일 통일하면서 같이 정하겠습니다

2023-12-24 12:05 UTC, Daybreak312 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controllers/pickle/PickleController.kt
> +@RequestMapping("/pickles")
추후에 다른 API도 복수형으로 바꾸겠습니다

2023-12-24 15:47 UTC, HyunSu1768 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/mapper/PickleMapper.kt
> +        pickleJpaEntity.id
scope 함수와 가독성을 위해 title = title 형식으로 작성하면 좋을것 같아요

2023-12-25 01:45 UTC, Daybreak312 approved these changes

2023-12-25 03:31 UTC, HyunSu1768 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/mapper/PickleMapper.kt
> +            id = pickleJpaEntity.id
scope 함수 써주세요

2023-12-25 07:48 UTC, merged