🔀 :: 피클 댓글 생성 기능
MaeumgaGym/MaeumGaGym_Backend pull request #78
Opened 2024-01-09 10:52 UTC by HyunSu1768

close #MA-97

2024-01-09 11:15 UTC, Daybreak312 requested changes

2024-01-09 11:15 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleCommentPersistenceAdapter.kt
> +    override fun readPickleComment(pickleCommentId: Long): PickleComment? =
Repository 함수명 인용하는 편이 나아보입니다. (findPickleCommentById 또는 readPickleCommentById)

2024-01-09 11:15 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleCommentJpaEntity.kt
> +    var childrenComments: MutableList<PickleCommentJpaEntity> = arrayListOf()
Mutable 대신 List 사용해주세요

2024-01-09 11:15 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/PickleCommentNotFoundException.kt
> +)
한 줄에 적어주세요

2024-01-09 11:15 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleCommentService.kt
> +        val comment = pickleCommentRequest.run {
변수 할당 제거해주세요

2024-01-09 11:15 UTC, Daybreak312 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/PickleCommentWebRequest.kt
> +    val parentId: Long?
해당 정보를 가공하기 위함이 아니라 어떠한 리소스에 접근하기 위함이므로 Body 대신 PathVariable에 위치하는 것이 좋아보입니다.

2024-01-09 11:15 UTC, Daybreak312 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/PickleCommentWebRequest.kt
> +    @field:NotNull(message = "null일 수 없습니다")
NotBlank로, 자료형은 Nullable로 바꿔주세요.

2024-01-09 11:15 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleCommentJpaEntity.kt
> +    @JoinColumn(name = "parent_commnet_id", nullable = true)
updatable=false 사용해주세요

2024-01-09 11:15 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleCommentJpaEntity.kt
> +    parentComment: PickleCommentJpaEntity?
기본값 null로 넣어주세요

2024-01-09 23:51 UTC, gurdl0525 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
> +        @NotEmpty(message = "parentId는 null이거나 값이 없을 수 없습니다.")
@Valid 어디감? 모든 검증 요소(파라미터)에 @Valid 붙여야 하는 것으로 알고 있습니다.
물론 안달아도 @Validated가 해주겠지만 @Valid 다는게 바람직 함으로 차라리 Validation 사용하지말고
@PathVariable이나 @RequestParam에서 제공하는 예외처리에 따르는게 나을 수도?

2024-01-09 23:53 UTC, HyunSu1768 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
> +        @NotEmpty(message = "parentId는 null이거나 값이 없을 수 없습니다.")
수정했습니다

2024-01-09 23:55 UTC, gurdl0525 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
> +        @Valid
요건 왜달아 놓은거?

2024-01-09 23:55 UTC, gurdl0525 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
> +        @Valid
그냥 제약 조건이 없는디?

2024-01-09 23:59 UTC, HyunSu1768 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
> +        @Valid
수정했씁니다

2024-01-09 23:59 UTC, gurdl0525 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
> +        parentId: Long?
nullable 타입 맞는지 확인해주세요

2024-01-10 00:00 UTC, gurdl0525 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
> +        parentId: Long?
이것만 수정하고 머지 ㄱㄱ

2024-01-10 00:04 UTC, HyunSu1768 commented on maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
> +        parentId: Long?
정신이 오락가락 하네요
수정했습니다.

2024-01-10 00:28 UTC, gurdl0525 approved these changes

2024-01-10 00:29 UTC, merged