✨ :: 댓글 조회 API 개발
MaeumgaGym/MaeumGaGym_Backend pull request #87
Opened 2024-01-11 01:41 UTC by HyunSu1768

- pickle 댓글 전체 조회 기능 개발

2024-01-11 02:03 UTC, gurdl0525 requested changes
• QueryDSL로 DB에서 DTO로 바로 불러올 수 있도록 할 것
• Paging 처리할 것
• 논리적으로 대댓글 까지만 존재 할 것

2024-01-11 05:48 UTC, Daybreak312 requested changes

2024-01-11 05:48 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/response/PickleCommentResponse.kt
> +            }
PickleComment의 메소드로 옮겨주세요
네이밍도 toResponse()로 바꿔주세요

2024-01-11 05:48 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/response/PickleCommentResponse.kt
> +    val createdAt: LocalDateTime?
createdAt은 Non Null Type이어야 합니다

2024-01-11 05:48 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/response/PickleCommentResponse.kt
> +    val writerId: UUID,
writerId가 아닌 UserResponse를 포함해야 합니다.

2024-01-11 05:48 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/response/PickleCommentResponse.kt
> +    val childrenComment: MutableList<PickleCommentResponse> = arrayListOf(),
유저가 해당 댓글의 대댓글을 펼쳐 보기할 때만 넘겨주면 됩니다.
다른 API로 따로 작성해주세요.

2024-01-11 05:48 UTC, Daybreak312 commented on maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleCommentService.kt
> +                    createdAt = LocalDateTime.now()
createdAt은 자동으로 할당됩니다.

2024-01-16 11:40 UTC, Daybreak312 requested changes

2024-01-16 11:40 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/mapper/PickleCommentMapper.kt
>      fun toEntity(pickleComment: PickleComment): PickleCommentJpaEntity {
domain, entity로 네이밍 통일해주세요
단일 표현식 함수 사용해주세요

2024-01-16 11:41 UTC, Daybreak312 requested changes

2024-01-16 11:41 UTC, Daybreak312 commented on maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleReplyPersistenceAdapter.kt
> +class PickleReplyPersistenceAdapter(
internal 달이주세요

2024-01-16 11:46 UTC, Daybreak312 approved these changes
LGTM 🤩

2024-01-16 11:56 UTC, gurdl0525 approved these changes

2024-01-16 11:59 UTC, merged